# Generated by Django 6.0 on 2026-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_user_order_tickets_alter_movie_actors_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickets',
            name='unique_row_seat_and_movie_session',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='rows',
            new_name='row',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='seats_in_row',
            new_name='seat',
        ),
        migrations.AddConstraint(
            model_name='tickets',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_tickets'),
        ),
    ]
